version: "3.8"
services:
  mongodb:
    image: mongo:5.0
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234

  app:
    image: user_service:local
    container_name: backend
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - mongodb



