AppVersion: 1.0.0

Server:
  Port: :5555
  Development: true
  Timeout: 15
  ReadTimeout: 5
  WriteTimeout: 5
  MaxConnectionIdle: 5
  MaxConnectionAge: 5


Http:
  Port: ":8000"
  PprofPort: ":8100"
  Timeout: 15
  ReadTimeout: 5
  WriteTimeout: 5
  CookieLifeTime: 44640
  SessionCookieName: "session_token"


#Kafka:
#  Brokers: [ "localhost:9091",  "localhost:9092",  "localhost:9093" ]

#Logger:
#  DisableCaller: false
#  DisableStacktrace: false
#  Encoding: json
#  Level: info

MongoDB:
  URI: "mongodb://localhost:27017/"
  DB: "fitnessApp"

