AppVersion: 1.0.0

Server:
  Port: :5555
  Development: true
  Timeout: 15
  ReadTimeout: 5
  WriteTimeout: 5
  MaxConnectionIdle: 5
  MaxConnectionAge: 5


Http:
  Port: ":8000"
  PprofPort: ":8100"
  Timeout: 15
  ReadTimeout: 5
  WriteTimeout: 5
  CookieLifeTime: 44640
  SessionCookieName: "session_token"

#Logger:
#  DisableCaller: false
#  DisableStacktrace: false
#  Encoding: json
#  Level: info

MongoDB:
  URI: "mongodb://admin:1234@mongodb:27017/?authSource=admin"
  DB: "fitnessApp"

AuthConfig:
  JWT:
    AccessTokenTTL: 15m
    RefreshTokenTTL: 720h
    SigningKey: "nf3823848h3290fb289"
  Salt: "3n92rn329fjids9"


